(function(){'use strict';var h=function(a){return"gwd-page"==a.tagName.toLowerCase()||"gwd-page"==a.getAttribute("is")},k=function(a){if(h(a))return a;for(;a&&9!=a.nodeType;)if((a=a.parentElement)&&h(a))return a;return null};var l=/[^\d]+$/;var n=function(a,e,d,b){if(0>=b)return a;if(1<=b)return e;switch(d){case "ease-in":d=b*b*b;break;case "ease-in-out":d=3*b*b-2*b*b*b;break;case "ease-out":d=1-b;d=1-d*d*d;break;default:d=b}return(e-a)*d+a},p=function(a,e,d,b,c){if(!a.hasAttribute(e))return d;var f=a.getAttribute(e);a=parseFloat(f);if(isNaN(a))return d;(d=(d=f.match(l))&&d[0]||null)&&(d=d.trim());f=a;if("%"==d)switch(e){case "width":case "xenter":case "xexit":f=Number((a/100*b).toFixed(2));break;case "height":case "yenter":case "yexit":f=
Number((a/100*c).toFixed(2))}return f},q=function(a,e){if(!a.hasAttribute(e))return 1;a=a.getAttribute(e);a=parseFloat(a);return isNaN(a)?1:0>a?0:1<a?1:a};var r=function(){};goog.inherits(r,HTMLElement);r.prototype.createdCallback=function(){this.f=[];this.c=this.o=null;this.a=[];this.h=this.v.bind(this);this.s=this.l=!1;this.g=this.w.bind(this);this.b=null};
r.prototype.attachedCallback=function(){Enabler.isServingInLiveEnvironment()?Enabler.addEventListener(studio.events.StudioEvent.HOSTPAGE_SCROLL,this.g,!1):window.addEventListener("message",this.g,!1);if("function"==typeof this.gwdLoad&&"function"==typeof this.gwdIsLoaded&&!this.gwdIsLoaded()){var a=k(this),e=a&&"function"==typeof a.gwdIsLoaded;(!a||e&&a.gwdIsLoaded())&&this.gwdLoad()}};
r.prototype.detachedCallback=function(){Enabler.isServingInLiveEnvironment()?Enabler.removeEventListener(studio.events.StudioEvent.HOSTPAGE_SCROLL,this.g,!1):window.removeEventListener("message",this.g,!1);this.removeEventListener("ready",this.h,!1)};
r.prototype.gwdLoad=function(){if(!this.gwdIsLoaded()){this.a.length=0;t(this);for(var a=this.a.length-1;0<=a;a--)this.a[a].gwdLoad();this.a=this.a.filter(function(a){return!a.gwdIsLoaded()});0==this.a.length?u(this):this.addEventListener("ready",this.h,!1)}};r.prototype.gwdIsLoaded=function(){return this.l&&0==this.a.length};r.prototype.v=function(a){a=this.a.indexOf(a.target);0<=a&&(this.a.splice(a,1),0==this.a.length&&(u(this),this.removeEventListener("ready",this.h,!1)))};
var u=function(a){if(!a.s){var e=document.createEvent("Event");e.initEvent("ready",!0,!0);a.dispatchEvent(e)}a.s=!0;a.b&&(v(a,a.b.creativeFramePercentY,a.b.windowHeight+a.c),a.b=null)},t=function(a){a.style.overflow="hidden";a.f.length=0;a.o=a.clientWidth;a.c=a.clientHeight;for(var e=a.ownerDocument,d=0;d<a.children.length;d++){var b=a.children[d],c=a.o,f=a.c,g=p(b,"xenter",0,c,f),m=p(b,"xexit",0,c,f),w=p(b,"yenter",0,c,f),x=p(b,"yexit",0,c,f),y=q(b,"opacityenter"),z=q(b,"opacityexit"),A=b.hasAttribute("fixed"),
B=b.getAttribute("assettype")||"",C=b.getAttribute("source")||"",D=b.getAttribute("easing")||"linear",E=p(b,"width",c,c,f);c=p(b,"height",f,c,f);b={u:B,easing:D,element:b,fixed:A,height:c,m:y,A:z,source:C,width:E,i:g,j:w,B:m,C:x};a.f.push(b);b.element.style.position="absolute";b.element.style.left="0px";b.element.style.top="0px";b.element.style.width=b.width+"px";b.element.style.height=b.height+"px";b.element.style.transform="translate("+b.i+"px, "+b.j+"px)";b.element.style.opacity=b.m+"";if("image"==
b.u&&b.source){for(;b.element.firstChild;)b.element.removeChild(b.element.firstChild);g=e.createElement("gwd-image");g.style.width="100%";g.style.height="100%";g.setAttribute("source",b.source);a.a.push(g);b.element.appendChild(g)}}a.l=!0};r.prototype.w=function(a){if(!Enabler.isServingInLiveEnvironment()){if(!a.data)return;a=JSON.parse(a.data);if(a.eventType!=studio.events.StudioEvent.HOSTPAGE_SCROLL)return}this.gwdIsLoaded()?v(this,a.creativeFramePercentY,a.windowHeight+this.c):this.b=a};
var v=function(a,e,d){for(var b=0;b<a.f.length;b++){var c=a.f[b];if(c.fixed){var f=c.i;var g=c.j+e*d}else f=n(c.i,c.B,c.easing,e),g=n(c.j,c.C,c.easing,e);var m=n(c.m,c.A,c.easing,e);c.element.style.transform="translate("+f+"px, "+g+"px)";c.element.style.opacity=m+""}};document.registerElement("gwd-parallax",{prototype:r.prototype});}).call(this);
